#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Detect and optionally run the repository's pre-commit-compatible hook runner."""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

MIN_ARGS_FOR_DIRECTORY = 2
KNOWN_TOOLS = ("prek", "pre-commit")
PREK_SIGNATURES = ("File generated by prek", "prek run")
PRE_COMMIT_SIGNATURES = ("File generated by pre-commit", "pre-commit run")


def _git_path(repo_path: Path, name: str) -> Path | None:
    """Resolve an effective Git path without stripping significant pathname whitespace."""
    try:
        result = subprocess.run(
            ["git", "-C", str(repo_path), "rev-parse", "--git-path", name],
            check=False,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return None
    if result.returncode != 0:
        return None
    value = result.stdout.removesuffix("\n")
    value = value.removesuffix("\r")
    if not value:
        return None
    path = Path(value)
    return path if path.is_absolute() else repo_path / path


def _tool_from_hook(hook_file: Path) -> str | None:
    """Identify a supported runner only from generated/invocation evidence."""
    if not hook_file.is_file():
        return None
    try:
        head = "\n".join(hook_file.read_text(encoding="utf-8", errors="replace").splitlines()[:20])
    except OSError:
        return None

    prek = any(signature in head for signature in PREK_SIGNATURES)
    pre_commit = any(signature in head for signature in PRE_COMMIT_SIGNATURES)
    if prek == pre_commit:
        return None
    return "prek" if prek else "pre-commit"


def detect_tool(repo_path: Path) -> tuple[str | None, str | None]:
    """Return (identified runner, error); never substitute a different PATH runner."""
    hook_path = _git_path(repo_path, "hooks/pre-commit")
    if hook_path is None:
        return None, "unable to resolve the effective Git pre-commit hook"

    identified = _tool_from_hook(hook_path)
    if identified is None:
        return None, "effective hook does not identify a supported generated runner"

    if shutil.which(identified) is None:
        return identified, f"repository identifies {identified}, but that executable is unavailable"

    return identified, None


def main() -> int:
    """Detect the intended runner and optionally execute it."""
    repo_path = Path.cwd()
    args = sys.argv[1:]

    if args and args[0] == "--directory":
        if len(args) < MIN_ARGS_FOR_DIRECTORY:
            print("Error: --directory requires a path argument", file=sys.stderr)
            return 2
        repo_path = Path(args[1])
        args = args[2:]

    tool, error = detect_tool(repo_path)
    if error is not None:
        prefix = f"{tool}: " if tool else ""
        print(f"{prefix}{error}; runner selection is incomplete.", file=sys.stderr)
        return 3

    assert tool is not None
    if not args:
        print(tool)
        return 0

    try:
        result = subprocess.run([tool, *args], check=False, cwd=repo_path)
    except FileNotFoundError:
        print(f"Error: {tool} not found in PATH", file=sys.stderr)
        return 127
    return result.returncode


if __name__ == "__main__":
    sys.exit(main())
