"""Tests for pre-commit-compatible runner detection."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path

import pytest

SCRIPT = Path(__file__).parents[1] / "skills" / "holistic-linting" / "scripts" / "detect_hook_tool.py"
SPEC = spec_from_file_location("detect_hook_tool", SCRIPT)
assert SPEC
assert SPEC.loader
MODULE = module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)
REAL_WHICH = shutil.which


def _runners_available(*available: str):
    """Fake runner availability while leaving Git discovery real."""
    return lambda name: REAL_WHICH(name) if name == "git" else (f"/bin/{name}" if name in available else None)


def _repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q", str(repo)], check=True)
    return repo


def _write_hook(repo: Path, content: str, hooks_path: str | None = None) -> Path:
    if hooks_path is not None:
        subprocess.run(["git", "-C", str(repo), "config", "core.hooksPath", hooks_path], check=True)
    result = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "--git-path", "hooks/pre-commit"],
        check=True,
        capture_output=True,
        text=True,
    )
    raw = result.stdout.removesuffix("\n")
    raw = raw.removesuffix("\r")
    hook = Path(raw)
    if not hook.is_absolute():
        hook = repo / hook
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_text(content, encoding="utf-8")
    return hook


def test_custom_hook_comment_is_not_framework_identity(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    repo = _repo(tmp_path)
    _write_hook(repo, "#!/bin/sh\n# Custom pre-commit checks\nexit 0\n")
    monkeypatch.setattr(MODULE.shutil, "which", _runners_available("prek", "pre-commit"))
    assert MODULE.detect_tool(repo)[0] is None


def test_identified_missing_runner_is_not_substituted(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    repo = _repo(tmp_path)
    _write_hook(repo, "#!/bin/sh\n# File generated by pre-commit: https://pre-commit.com\n")
    monkeypatch.setattr(MODULE.shutil, "which", _runners_available("prek"))
    tool, error = MODULE.detect_tool(repo)
    assert tool == "pre-commit"
    assert error
    assert "unavailable" in error


def test_significant_hooks_path_whitespace_is_preserved(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    repo = _repo(tmp_path)
    hook = _write_hook(repo, "#!/bin/sh\n# File generated by prek\n", hooks_path=" hooks")
    assert hook.parent.name == " hooks"
    monkeypatch.setattr(MODULE.shutil, "which", _runners_available("prek"))
    assert MODULE.detect_tool(repo) == ("prek", None)


def test_cli_returns_incomplete_when_identified_runner_is_missing(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _repo(tmp_path)
    _write_hook(repo, "#!/bin/sh\n# File generated by pre-commit: https://pre-commit.com\n")
    empty_bin = tmp_path / "bin"
    empty_bin.mkdir()
    git = shutil.which("git")
    assert git is not None
    (empty_bin / "git").symlink_to(git)
    result = subprocess.run(
        [sys.executable, str(SCRIPT), "--directory", str(repo)],
        check=False,
        capture_output=True,
        text=True,
        env={**os.environ, "PATH": str(empty_bin)},
    )
    assert result.returncode == 3
    assert "unavailable" in result.stderr


def test_cli_returns_incomplete_when_git_is_unavailable(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    _write_hook(repo, "#!/bin/sh\n# File generated by prek\n")
    empty_bin = tmp_path / "bin"
    empty_bin.mkdir()
    result = subprocess.run(
        [sys.executable, str(SCRIPT), "--directory", str(repo)],
        check=False,
        capture_output=True,
        text=True,
        env={**os.environ, "PATH": str(empty_bin)},
    )
    assert result.returncode == 3
    assert "runner selection is incomplete" in result.stderr
