#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Generate harness_compatibility.json from the plugins/ tree.

Objective fields (manifests present, runtime-escape blockers) are re-derived from the
filesystem on every run so the table cannot drift. Subjective fields (per-harness
verification status, dates, notes) are preserved from the existing table when present.

Usage:
    uv run --script scripts/generate_harness_compatibility.py [--check]

Exit codes:
    0: table written (or --check: table is current)
    1: --check: table is stale, regenerate
"""

from __future__ import annotations

import argparse
import contextlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLUGINS_DIR = ROOT / "plugins"
TABLE_PATH = ROOT / "harness_compatibility.json"

HARNESSES = ["claude-code", "codex", "hermes", "kimi"]


def count_token_uses(plugin_dir: Path, token: str) -> int:
    """Count occurrences of a substitution token in runtime text.

    Args:
        plugin_dir: Plugin root directory.
        token: Literal token to count (e.g. ``${CLAUDE_PLUGIN_ROOT}``).

    Returns:
        Total occurrences across ``skills/``, ``agents/``, and ``commands/`` markdown.
    """
    total = 0
    for subdir in ("skills", "agents", "commands"):
        d = plugin_dir / subdir
        if not d.is_dir():
            continue
        for f in d.rglob("*.md"):
            with contextlib.suppress(OSError, UnicodeDecodeError):
                total += f.read_text(encoding="utf-8").count(token)
    return total


def scan_plugin(plugin_dir: Path) -> dict:
    """Derive the objective table entry for one plugin from the filesystem.

    Returns:
        Mapping with ``manifests``, ``components``, and ``blockers`` sections.
    """
    mcp_server_count = 0
    for p in (plugin_dir / ".mcp.json", plugin_dir / "mcp.json"):
        if p.exists():
            try:
                mcp_server_count += len(json.loads(p.read_text(encoding="utf-8")).get("mcpServers", {}))
            except (json.JSONDecodeError, OSError) as exc:
                print(
                    f"warning: {plugin_dir.name}: cannot parse {p.name} ({exc}); counting 0 MCP servers",
                    file=sys.stderr,
                )
    return {
        "manifests": {
            "claude": (plugin_dir / ".claude-plugin" / "plugin.json").exists(),
            "codex": (plugin_dir / ".codex-plugin" / "plugin.json").exists(),
            "portable": (plugin_dir / "plugin.json").exists(),
            "hermes_native": (plugin_dir / "plugin.yaml").exists(),
        },
        "components": {
            "skills": len(list((plugin_dir / "skills").glob("*/SKILL.md"))) if (plugin_dir / "skills").is_dir() else 0,
            "agents": len(list((plugin_dir / "agents").glob("*.md"))) if (plugin_dir / "agents").is_dir() else 0,
            "mcp_servers": mcp_server_count,
            "hooks": (plugin_dir / "hooks").is_dir() and any((plugin_dir / "hooks").iterdir()),
        },
        "blockers": {
            "claude_plugin_root_uses": count_token_uses(plugin_dir, "${CLAUDE_PLUGIN_ROOT}"),
            "claude_skill_dir_uses": count_token_uses(plugin_dir, "${CLAUDE_SKILL_DIR}"),
        },
    }


def preserve_verification(old: dict, name: str) -> dict:
    """Carry hand-maintained verification entries over from the previous table.

    Returns:
        Per-harness verification mapping, defaulting to ``unverified``.
    """
    prev = old.get("plugins", {}).get(name, {}).get("verification", {})
    default = {"status": "unverified", "date": None, "notes": None}
    if not isinstance(prev, dict):
        prev = {}
    out = {}
    for h in HARNESSES:
        entry = prev.get(h)
        out[h] = entry if isinstance(entry, dict) and "status" in entry else dict(default)
    return out


def build_table() -> dict:
    """Scan every plugin and assemble the full table, preserving verification state.

    Returns:
        The complete table document as a JSON-serializable mapping.
    """
    old = {}
    if TABLE_PATH.exists():
        old = json.loads(TABLE_PATH.read_text(encoding="utf-8"))
    plugins = {}
    for plugin_dir in sorted(p for p in PLUGINS_DIR.iterdir() if p.is_dir() and not p.name.startswith((".", "_"))):
        if not (plugin_dir / ".claude-plugin").is_dir() and not (plugin_dir / "skills").is_dir():
            continue  # not a plugin
        entry = scan_plugin(plugin_dir)
        entry["verification"] = preserve_verification(old, plugin_dir.name)
        plugins[plugin_dir.name] = entry
    return {
        "_about": (
            "Cross-harness compatibility table. 'manifests'/'components'/'blockers' are generated by "
            "scripts/generate_harness_compatibility.py from the filesystem — do not hand-edit. "
            "'verification' is hand-maintained: set status to 'verified' with the ISO date and the "
            "issue/PR reference in notes after running the smoke tests named in that harness's issue."
        ),
        "harnesses": HARNESSES,
        "plugins": plugins,
    }


def main() -> int:
    """Entry point: write the table, or check staleness with ``--check``.

    Returns:
        Process exit code: 0 on success/current, 1 when ``--check`` finds a stale table.
    """
    parser = argparse.ArgumentParser(description="Generate harness_compatibility.json from the plugins/ tree.")
    parser.add_argument("--check", action="store_true", help="exit 1 if the committed table is stale")
    args = parser.parse_args()

    table = build_table()
    rendered = json.dumps(table, indent=2, ensure_ascii=False) + "\n"
    if args.check:
        # Compare parsed content, not bytes: the repo's JSON formatter hooks (biome) may
        # reflow the committed file, and cosmetic reflow is not staleness.
        current_text = TABLE_PATH.read_text(encoding="utf-8") if TABLE_PATH.exists() else ""
        try:
            current = json.loads(current_text) if current_text else None
        except json.JSONDecodeError:
            current = None
        if current != table:
            print(
                "harness_compatibility.json is stale; run: uv run --script scripts/generate_harness_compatibility.py",
                file=sys.stderr,
            )
            return 1
        print("harness_compatibility.json is current")
        return 0
    TABLE_PATH.write_text(rendered, encoding="utf-8")
    n = len(table["plugins"])
    print(f"wrote {TABLE_PATH.relative_to(ROOT)} ({n} plugins)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
