#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# ///
"""Render finalized daily-release analysis as Markdown."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

CATEGORY_TITLES = {
    "bug_fixes": "Bug Fixes",
    "enhancements": "Enhancements",
    "tech_debt": "Technical Debt",
    "documentation": "Documentation",
    "testing": "Testing",
    "build_ci": "Build and CI",
    "non_functional": "Non-functional",
}


def _entry_line(entry: dict[str, object] | str) -> str:
    """Render one categorized change.

    Returns:
        A Markdown list item.
    """
    if isinstance(entry, str):
        return f"- {entry}"
    title = entry.get("title") or entry.get("change") or entry.get("type") or "Change"
    description = entry.get("description") or entry.get("benefits") or entry.get("impact")
    return f"- **{title}**: {description}" if description else f"- **{title}**"


def format_release_notes(analysis: dict[str, object]) -> str:
    """Render a finalized analysis object as release-note Markdown.

    Returns:
        The release-note Markdown.
    """
    stats = analysis.get("statistics", {})
    stats = stats if isinstance(stats, dict) else {}
    lines = [
        f"# {analysis.get('title', 'Daily Release')}",
        "",
        "## Summary",
        "",
        str(analysis.get("summary", "")),
        "",
        "## Statistics",
        "",
        f"- **Commits**: {stats.get('commit_count', stats.get('commits', 0))}",
        f"- **Files Changed**: {stats.get('files_changed', 0)}",
        f"- **Lines Added**: +{stats.get('lines_added', 0)}",
        f"- **Lines Deleted**: -{stats.get('lines_deleted', 0)}",
    ]

    categories = analysis.get("change_categories", {})
    categories = categories if isinstance(categories, dict) else {}
    rendered_categories = [(key, values) for key, values in categories.items() if isinstance(values, list) and values]
    if rendered_categories:
        lines.extend(("", "## Changes by Category"))
        for key, entries in rendered_categories:
            lines.extend(("", f"### {CATEGORY_TITLES.get(key, key.replace('_', ' ').title())}", ""))
            lines.extend(_entry_line(entry) for entry in entries if isinstance(entry, (dict, str)))

    components = analysis.get("components_affected", [])
    components = components if isinstance(components, list) else []
    if components:
        lines.extend(("", "## Components Affected", ""))
        lines.extend(f"- `{component}`" for component in components)

    breaking_changes = analysis.get("breaking_changes", [])
    breaking_changes = breaking_changes if isinstance(breaking_changes, list) else []
    if breaking_changes:
        lines.extend(("", "## Breaking Changes", ""))
        lines.extend(_entry_line(change) for change in breaking_changes)

    lines.extend(("", "---", "", "*Generated by the `daily-releases` skill.*", ""))
    return "\n".join(lines)


def main() -> int:
    """Run the release-note formatter CLI.

    Returns:
        A process exit status.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("analysis_file", type=Path)
    parser.add_argument("--output", "-o", type=Path, required=True)
    args = parser.parse_args()
    try:
        analysis = json.loads(args.analysis_file.read_text(encoding="utf-8"))
        description = format_release_notes(analysis)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(description, encoding="utf-8")
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(json.dumps({"error": str(error)}), file=sys.stderr)
        return 1
    print(json.dumps({"output_file": str(args.output.resolve())}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
